apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  