version: "3.9"

services:
  java_db:
    container_name: sqlserver_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 14033:1433
    environment:
      ACCEPT_EULA: Y
      SA_USER: sa
      SA_PASSWORD: 980Parace12tamol%&
      SA_DB: postgres